eureka:
  password: s3cret
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@10.53.30.132:8761/eureka/

zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      serviceId: ms-users
  strip-prefix: false
