eureka:
  password: s3cret
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@ec2-13-57-34-187.us-west-1.compute.amazonaws.com:8761/eureka/

zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      serviceId: ms-users
  strip-prefix: false
